#docker-compose up -d --scale springboot-app=5 Crea 5 instancias del mismo servicio
version: '3'
services:
  springboot-app:
    image: microservicetest
    #restart: always
    ports:
      - 8080:8080
      #- 8000-8999:8080
    networks:
      - microservicetest
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: microserviceTest
  mysqldb:
    container_name: mysqldb
    image: mysql
    networks:
      - microservicetest
    volumes:
      - ./database/persistence:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: microserviceTest
      MYSQL_ROOT_PASSWORD: root
networks:
  microservicetest:
